using System.Collections.Generic;
using System.Xml.Linq;

using Avalonia.NameGenerator.VisualBasic.Domain;
using XamlX.TypeSystem;

namespace Avalonia.NameGenerator.VisualBasic.Generator;

internal class InitializeComponentCodeGenerator: ICodeGenerator
{
    private readonly bool _diagnosticsAreConnected;
    private const string AttachDevToolsCodeBlock = @"
#If DEBUG Then

        ' Attach dev tools (if Avalonia.Diagnostics package is referenced).
        If (attachDevTools) Then
            MyBase.AttachDevTools()
        End If

#End If
";
    private const string AttachDevToolsParameterDocumentation
        = @"    ' <param name=""attachDevTools"">Should the dev tools be attached.</param>
";

    public InitializeComponentCodeGenerator(IXamlTypeSystem types)
    {
        _diagnosticsAreConnected = types.FindAssembly("Avalonia.Diagnostics") != null;
    }

    public string GenerateCode(string className, string nameSpace, IXamlType xamlType, IEnumerable<ResolvedName> names)
    {
        var properties = new List<string>();
        var initializations = new List<string>();
        foreach (var resolvedName in names)
        {
            var (typeName, name, fieldModifier) = resolvedName;
            properties.Add($"    {fieldModifier} Property {name} As {typeName}");
            initializations.Add($"        {name} = FindNameScope().Find(Of {typeName})(\"{name}\")");
        }

        var attachDevTools = _diagnosticsAreConnected && IsWindow(xamlType);

        return $@"' <auto-generated />

Imports Avalonia
Imports Avalonia.Controls
Imports Avalonia.Markup.Xaml

Partial Public Class {className}

{string.Join("\n", properties)}

    ' <summary>
    ' Wires up the controls and optionally loads XAML markup and attaches dev tools (if Avalonia.Diagnostics package is referenced).
    ' </summary>
    ' <param name=""loadXaml"">Should the XAML be loaded into the component.</param>
{(attachDevTools ? AttachDevToolsParameterDocumentation : string.Empty)}
    Private Sub InitializeComponent(Optional loadXaml As Boolean = True{(attachDevTools ? ", Optional attachDevTools As Boolean = True" : string.Empty)})
        
        If loadXaml Then
            AvaloniaXamlLoader.Load(Me)
        End If

{(attachDevTools ? AttachDevToolsCodeBlock : string.Empty)}
{string.Join("\n", initializations)}

    End Sub

End Class
";
    }
        
    private static bool IsWindow(IXamlType xamlType)
    {
        var type = xamlType;
        bool isWindow;
        do
        {
            isWindow = type.FullName == "Avalonia.Controls.Window";
            type = type.BaseType;
        } while (!isWindow && type != null);

        return isWindow;
    }
}